# Generated by Django 4.0.4 on 2022-04-25 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkpriceinformation',
            old_name='purchasing_date',
            new_name='confirmation_date',
        ),
    ]
