# Generated by Django 4.0.4 on 2022-04-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0002_rename_purchasing_date_drinkpriceinformation_confirmation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkpriceinformation',
            name='aged',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
