# Generated by Django 4.0.4 on 2022-04-25 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0004_alter_drinkpriceinformation_recoding_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drinkpriceinformation',
            name='recoding_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
