# Generated by Django 4.0.4 on 2022-04-25 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0005_alter_drinkpriceinformation_recoding_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkpriceinformation',
            old_name='recoding_date',
            new_name='recoded_date',
        ),
    ]
