# Generated by Django 4.0.4 on 2022-04-25 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0007_drinkpriceinformation_note'),
    ]

    operations = [
        migrations.RenameField(
            model_name='drinkpriceinformation',
            old_name='category',
            new_name='category_1',
        ),
        migrations.AddField(
            model_name='drinkpriceinformation',
            name='category_2',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
