# Generated by Django 4.0.4 on 2022-04-26 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0008_rename_category_drinkpriceinformation_category_1_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DrinkPriceInformation',
            new_name='LiqueurPriceInformation',
        ),
    ]
