# Generated by Django 4.0.4 on 2022-04-27 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market_price', '0009_rename_drinkpriceinformation_liqueurpriceinformation'),
    ]

    operations = [
        migrations.RenameField(
            model_name='liqueurpriceinformation',
            old_name='name',
            new_name='liqueur_name',
        ),
    ]
