# Generated by Django 4.0.4 on 2022-05-02 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0002_alter_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(null=True, upload_to='profile_wallpaper/'),
        ),
    ]
