# Generated by Django 4.0.4 on 2022-05-05 06:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profile_app', '0003_profile_wallpaper'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='profile_image/'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='introduce',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='nickname',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='wallpaper',
            field=models.ImageField(blank=True, null=True, upload_to='profile_wallpaper/'),
        ),
    ]
